app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/ 

Route::group(['middleware' => 'web'], function () {
	Route::get('/', 'HomeController@index');
    Route::get('/home', 'GuestController@index');
    Route::auth();

	Route::resource('students', 'StudentController');
	Route::resource('courses', 'CourseController');
	Route::resource('instructors', 'InstructorController');
	Route::get('answer','AnswerController@index');
});

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $fillable = [
        'name', 'email', 'password', 'gender', 'active'
    ];

    public function courses(){
        return $this->belongstoMany('App\Course','course_student','student_id','course_id');
    }

}
 

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Student;
use Yajra\Datatables\Html\Builder;
use Yajra\Datatables\Datatables;
use Input;
use Session; 
use Validator;  

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, Builder $htmlBuilder)
    {
        if($request -> ajax()) {
            $students = Student::select('name','email','gender','active');
            return Datatables::of($students) -> addColumn('action', function($student){
                return view('datatable.action', [
                    'model'    => $student,  
                    'delete_url' => route('students.destroy', $student->id),
                    'edit_url' => route('students.edit', $student->id),   
                    'confirm_message' => 'Yakin mau menghapus ' . $student->name . '?',
                ]);
            }) -> make(true);
        }
        $html = $htmlBuilder
                ->addColumn(['data' => 'name', 'name'=>'name', 'title' => 'Name'])
                ->addColumn(['data' => 'email', 'name'=>'email','title'=>'Email'])
                ->addColumn(['data' => 'gender', 'name'=>'gender','title'=>'Gender'])
                ->addColumn(['data' => 'active', 'name'=>'active','title'=>'Active'])
                ->addColumn(['data' => 'action', 'name'=>'action','title'=>'','orderable'=>false,'searchable'=>false]);

        return view('students.index') -> with(compact('html'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'name' => 'required|string|max:255|unique:students',
            'email' => 'required|string|email|max:255|unique:students',
            'password' => 'required|min:6',
            'gender' => 'required|string',
            'active' => 'required|integer'
        ];

        $messages = [
            'required' => 'Data tidak boleh kosong',
            'email' => 'Email tidak valid',
            'email.unique' => 'Email sudah ada dalam database.',
            'password.min' => 'Password minimal 6 karakter',
        ];

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return redirect() -> route('students.create')
                            ->withErrors($validator)
                            ->withInput();
        }

        $student = new Student;
        $student->name = $request->name;
        $student->email = $request->email;
        $student->password = bcrypt($request->password);
        $student->gender = $request->gender;
        $student->active = '1';
        $student->save();

        Session::flash('flash_notification', ["level"=>"success", "message"=>"Berhasil menambahkan ".$student -> name." kedalam database"]);
        return redirect() -> route('students.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::find($id);
        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $rules = [
            'name' => 'required|string|max:255|unique:students,name,'.$id,
            'email' => 'required|string|email|max:255|unique:students,email,'.$id,
            'password' => 'required|min:6',
            'gender' => 'required|string',
            'active' => 'required|integer'
        ];

        $messages = [
            'required' => 'Data tidak boleh kosong',
            'email' => 'Email tidak valid',
            'email.unique' => 'Email sudah ada dalam database.',
            'password.min' => 'Password minimal 6 karakter',
        ];

        $student = Student::find($id);
        $old_name = $student->name;

        $validator = Validator::make($request->all(), $rules, $messages);
        if ($validator->fails()) {
            return redirect() -> route('students.create')
                            ->withErrors($validator)
                            ->withInput();
        }

        $student->update($request->all());
         Session::flash("flash_notif",[
            "level" => "success",
            "message" => "Berhasil mengubah ".$old_name." menjadi ".$student->name." kedalam database"
        ]);
        return redirect() -> route('students.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::find($id);
        $name_student = $student -> name;
        
        if(!Student::destroy($id)) {
            return redirect() -> back();
        }

        Session::flash("flash_notif", [
            "level" => "success",
            "message" => "Siswa bernama ".$name_student." berhasil dihapus"
        ]);
        return redirect()->route('students.index');
    }
}

resources/views/students/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ route('students.index') }}">Student</a></li>
					<li class="active">Add Student</li>
				</ul> 
				<div class="panel panel-default">
					<div class="panel-heading">
					<h2 class="panel-title">Add Student</h2>
					</div>
					<div class="panel-body">
					{!! Form::open(['url' => route('students.store'),
					'method' => 'post', 'class'=>'form-horizontal']) !!}
					{!! csrf_field() !!} 
					
					@include('students.form') 

					{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/students/edit.blade.php
@extends('layouts.app') 
	@section('content')
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="{{ url('/home') }}">Dashboard</a></li>
						<li><a href="{{ route('students.index')  }}">Student</a></li>
						<li class="active">Edit Student</li>
					</ul>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2 class="panel-title">Edit Student</h2>
						</div>
						<div class="panel-body">
							{!! Form::model($student, ['url' => route('students.update', $student->id),
							'method'=>'put', 'class'=>'form-horizontal']) !!}

							@include('students.form')

							{!! Form::close() !!}
						</div> 
					</div>
				</div>
			</div>
		</div>
	@endsection

resources/views/students/form.blade.php
<div class= " form-group { !! $errors->has('name') ? 'has-error' : '' !!}">
	{!! Form::label('name', 'Full Name') !!}
	{!! Form::text('name', null, ['class' =>'form-control', 'placeholder' => 'Ketik nama lengkap...']) !!}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div> 

<div class= " form-group { !! $errors->has('email') ? 'has-error' : '' !!}">
	{!! Form::label('email', 'Email') !!}
	{!! Form::email('email', null, ['class' =>'form-control', 'placeholder' => 'Ketik email valid...']) !!}
	{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group { !! $errors->has('password') ? 'has-error' : '' !!}">
	{!! Form::label('password', 'Password') !!}
	{!! Form::password('password', null, ['class' =>'form-control']) !!}
	{!! $errors->first('password', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group { !! $errors->has('gender') ? 'has-error' : '' !!}">
	{!! Form::label('gender', 'Gender') !!}
	{!! Form::select('gender', ['male' => 'male', 'female' => 'female']); !!}
	{!! $errors->first('gender', '<p class="help-block">:message</p>') !!}
</div>

<div class= " form-group { !! $errors->has('active') ? 'has-error' : '' !!}">
	{!! Form::label('active', 'Active') !!}
	{!! Form::select('active', [1 => 1, 0 => 0]); !!}
	{!! $errors->first('active', '<p class="help-block">:message</p>') !!}
</div>

{!! Form::submit( isset( $model) ? 'Update' : 'Save', [ 'class'=> 'btn btn-primary']) !!}

resources/views/students/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Student</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Student List</h2>
					</div>
					<div class="panel-body">
						<p><a class="btn btn-primary" href=" {{ route('students.create') }}">Add</a></p>
						{!! $html -> table(['class' => 'table-striped']) !!}
					</div>
				</div>
			</div>
		</div>
	</div> 
@endsection 

@section('scripts')
	{!! $html -> scripts() !!}
@endsection