app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/ 

Route::group(['middleware' => 'web'], function () {
	Route::get('/', 'HomeController@index');
    Route::get('/home', 'GuestController@index');
    Route::auth();

	Route::resource('students', 'StudentController');
	Route::resource('courses', 'CourseController');
	Route::resource('instructors', 'InstructorController');
	Route::get('answer','AnswerController@index');
});

resources/views/courses/create.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li><a href="{{ route('courses.index') }}">Course</a></li>
					<li class="active">Add Course</li>
				</ul> 
				<div class="panel panel-default">
					<div class="panel-heading">
					<h2 class="panel-title">Add Course</h2>
					</div>
					<div class="panel-body">
					{!! Form::open(['url' => route('courses.store'),
					'method' => 'post', 'class'=>'form-horizontal']) !!}
					{!! csrf_field() !!} 
					
					@include('courses.form') 

					{!! Form::close() !!}
					</div>
				</div>
			</div>
		</div>
	</div>
@endsection

resources/views/courses/edit.blade.php
@extends('layouts.app') 
	@section('content')
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<ul class="breadcrumb">
						<li><a href="{{ url('/home') }}">Dashboard</a></li>
						<li><a href="{{ route('courses.index')  }}">Course</a></li>
						<li class="active">Edit Course</li>
					</ul>
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2 class="panel-title">Edit Course</h2>
						</div>
						<div class="panel-body">
							{!! Form::model($course, ['url' => route('courses.update', $course->id),
							'method'=>'put', 'class'=>'form-horizontal']) !!}

							@include('courses.form')

							{!! Form::close() !!}
						</div> 
					</div>
				</div>
			</div>
		</div>
	@endsection

resources/views/courses/form.blade.php
<div class= " form-group { !! $errors->has('name') ? 'has-error' : '' !!}">
	{!! Form::label('name', 'Title') !!}
	{!! Form::text('name', null, ['class' =>'form-control', 'placeholder' => 'Ketik nama buku...']) !!}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div> 

<div class= " form-group { !! $errors->has('description') ? 'has-error' : '' !!}">
	{!! Form::label('description', 'Description') !!}
	{!! Form::textarea('description', null, ['class' =>'form-control', 'placeholder' => 'Ketik deskripsi buku...']) !!}
	{!! $errors->first('description', '<p class="help-block">:message</p>') !!}
</div>	


{!! Form::submit( isset( $model) ? 'Update' : 'Save', [ 'class'=> 'btn btn-primary']) !!}

resources/views/courses/index.blade.php
@extends('layouts.app')

@section('content')
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<ul class="breadcrumb">
					<li><a href="{{ url('/home') }}">Dashboard</a></li>
					<li class="active">Courses</li>
				</ul>
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2 class="panel-title">Courses List</h2>
					</div>
					<div class="panel-body">
						<p><a class="btn btn-primary" href=" {{ route('courses.create') }}">Add</a></p>
						{!! $html -> table(['class' => 'table-striped']) !!}
					</div>
				</div>
			</div>
		</div>
	</div> 
@endsection 

@section('scripts')
	{!! $html -> scripts() !!}
@endsection